### ISSUE TITLE
python-openssl vs python3-openssl

### ISSUE THREAD

**Issue by mrdrparker** [mpedramfar/Lean-game-maker#24]
Hello,
When installing the `python-openssl` package, is it okay to use the `python3-openssl` package instead?
Thanks!

**Comment by mpedramfar** [comment]
Hi,
This, and several other packages that are listed in the installation guide, are system-wide libraries that are common and might be useful. Basically, everything under the heading "Python 3.7" in the installation guide is just to have a good python environment running. You can do it in many different ways and you can skip it if you have python and know how to set up a virtual environment.
This specific package is not used in Lean-game-maker.
