### ISSUE TITLE
Save in local storage / IndexedDB the contents of all editors

### ISSUE THREAD

**Issue by RaitoBezarius** [mpedramfar/Lean-game-maker#3]
This could be awesome if it was possible to save progression on games without having the tab open anytime.

Or at least to offer a way to export all editor contents from JavaScript for archiving purpose (like I want to keep my proofs of all my levels).

I can send some PR to do it if you think that's not too hard (I have expertise in React.js).

**Comment by RaitoBezarius** [comment]
It seems like that `game_data` is holding the whole state, now we only have to save this in localStorage and restore it, that sounds super simple.

**Comment by mpedramfar** [comment]
That would be great. As you mentioned, the `game_data` variable is all that matters. I was thinking about the following solution.

- When page loads for the first time, check the cookies. If there is a `game_data` variable with the same name and version as the original empty `game_data` then use that instead.
- Any time there is a change, save the `game_data` to the cookies.
- Add three buttons to the main page, `new game`, `load game`, and `save game`.
  - `new game` would delete the `game_data` from cookies and reloads the page.
  - `load game` would allow the user to upload a json file that contains the `game_data`. If the name and the version match, then put that in the cookies and reload the page.
  - `save game` would allow the user to download a file containing the `game_data`.
- Remove the question asking the user to confirm if they want to leave the page. (After all, everything is saved in the cookies, so the user will simply continue the game after reopening the page.)

Implementing it would be straightforward, but I'm very busy at the moment. If you would like to implement it, I would appreciate it.

**Comment by kim-em** [comment]
I think new/load/save is a bit complicated, and in any case _so_ last century. :-) I think @RaitoBezarius was just proposing dumping everything in localStorage automatically, and automatically pulling it back out. No user interface, no user action, but your old proofs are just still there.

**Comment by mpedramfar** [comment]
Fair point :)
I'll implement it in a few weeks.

**Comment by mpedramfar** [comment]
Saving the game progress in localStorage is added now.
