### ISSUE TITLE
folding spoilers?

### ISSUE THREAD

**Issue by kbuzzard** [mpedramfar/Lean-game-maker#5]
In the natural number game I am unfortunately very verbose, and sometimes I also give out spoilers. Would it be possible to fold comments away somehow, and somehow mark them as spoilers?

**Comment by mpedramfar** [comment]
That should be easy to implement. I'll add it, probably next week.

**Comment by mpedramfar** [comment]
Folding hints are now added. The usage syntax is in the usage guide.
