### ISSUE TITLE
Latex formatting issue

### ISSUE THREAD

**Issue by stanescuUW** [mpedramfar/Lean-game-maker#7]
Latex commands embedded in Lean comments don't always display properly. In particular, issues arise _sometimes_ when using the underscore for Latex subscripts. An example of the issue can be seen in the first level in "Limits" in the following build:
https://wwwf.imperial.ac.uk/~buzzard/xena/rng_20200412/
To reproduce the issue, clone the repository: https://github.com/ImperialCollegeLondon/real-number-game.git. In the src/game/limits, the file `L01defs_completeLatex.lean` which showcases the issue should be used (instead of the `L01defs.lean` in which the Latex commands causing the issue were cleared). I noticed the issue when building the Lean-game-maker with both Python 3.7.2 and 3.8.0. The mathlib library was version 3.8.0; npm version 6.14.4.

**Comment by mpedramfar** [comment]
Thanks! Fixed in the last commit.
