### ISSUE TITLE
Some Latex problems still persist 

### ISSUE THREAD

**Issue by stanescuUW** [mpedramfar/Lean-game-maker#8]
While the latest commit fixed most Latex problems, there are still some issues when Latex is embedded in comments, particularly after Markdown is used to delineate titles etc. Please see the same repository, level 1 in Sup/Inf, for an example. The first line after subtitle is dispayed as `Let $X$ be a set of real numbers.`

**Comment by mpedramfar** [comment]
I couldn't replicate the issue. Could you check it again? Does the issue persist after reloading the page, or going to another level and coming back? Could you provide more details?

**Comment by stanescuUW** [comment]
This must have happened when re-making and re-loading the game several times. I couldn't replicate it either after I restarted server and re-compiled everything. Closing it for now.

**Comment by stanescuUW** [comment]
I have eventually been able to reproduce it. Latex math display works well if loading from scratch. Issues arise if one uses the "Restart" button. You should be able to replicate the problem by loading the game, going through at least levels 1 and 2 in Sup/Inf (third world currently) then hit "Restart", go to Main menu and reload level 1. See attached snapshot.

![level2](https://user-images.githubusercontent.com/28028870/79802845-0424ce80-831e-11ea-9e2d-d962bb3cad96.png)

**Comment by mpedramfar** [comment]
That's strange. I still can't replicate it. When this happens, could you go to the browser console (Tools > Web Developer > Web Console in Firefox) and type `MathJax`? Let me know if is says `undefined` or not. If it's not `undefined`, then try typing `MathJax.Hub.Queue(["Typeset",MathJax.Hub]);` and let me know if the LaTeX works.
Also, when this happens, if you go to another level and come back, will it load the LaTeX properly?

MathJax works asynchronously. When I open a level, sometimes it takes a fraction of a second before it starts working. Could it be the case that it takes longer in your browser?

**Comment by stanescuUW** [comment]
OK, it took me some time to track this. It appears it is browser-dependent. If I make the game from scratch, start the local server then load the game in Opera, go through a few levels then reset, the problem arises. The exactly same process in Firefox leads to no problem. Didn't try in other browsers. Let me know if you think we should pursue this further.

**Comment by mpedramfar** [comment]
Thank you! I was able to replicate the issue in Opera. Apparently the relative speed of loading different modules could cause problems in rendering LaTeX. I made some changes which solved the issue for me. If you have time to check, let me know if the issue persists.

**Comment by stanescuUW** [comment]
It does persist on my end. I did rebuild the game maker and I have the latest version of Opera, running on a Latex machine. It may not be that important, because Opera is not very widely used. 

Could it be related to the following warning messages I get when building the game maker (and if yes, how do I fix those?):
```
npm WARN terser-webpack-plugin-legacy@1.2.3 requires a peer of webpack@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN make-lean-game@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 6463 packages in 14.844s

23 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by mpedramfar** [comment]
Just to double check, did you clean the cache before running the game again? Browsers will cache to optimise loading time. If you clear the recent history (including site data), then you can be sure that the browser isn't running the old version from cache.

As for the warnings you mentioned, I get the same warnings. They're harmless and not related to LaTeX rendering.
The issue I found, and fixed in the last commit, was that if the MathJax module was downloaded and run by the browser faster than some other components of the game, then LaTeX may not be rendered. Apparently this could depend on the browser, on whether the game is being run locally or not, the relative speed of the connection of the user to the website hosting the game in comparison with the website hosting the MathJax library, etc.

**Comment by stanescuUW** [comment]
I also thought about all these variables you mention. Nevertheless, clearing the cache did fix the issue in Opera. In my experience, Firefox did best when rendering this game (better than Chrome, Safari and Opera). If that is also your experience, maybe it should be mentioned somewhere.

Thank you for this great contribution!

**Comment by mpedramfar** [comment]
This code is a wrapper around Lean and I believe Lean works best in Chrome. Although I've rarely seen any issues in Firefox. I'll mention this in the README file.

Thank you for using this library to make more games!
